# # Loop 
# expenses = [10.50, 8, 5, 15, 20, 5, 3]
# sum = 0 
# for x in expenses:
#     sum = sum + x
# print(sum)

# Example 
expenses = [10.50, 8, 5, 15, 20, 5, 3]

total = sum(expenses)

print('You spent $', total, sep = '') # to remmove the space after $ - Seperator 

# Example range() Function 
range(7)
range(0, 7, 1) # start, stop, step
range(2, 14, 2)

# we can then use a for loop like we've seen with sequence generated by range()
# This let's us loop a certain number of times, which is what needed to enter expenses...
# asking users to enter 7 times in loop  
total = 0 
expenses = []
for i in range(7):
    expenses.append(float(input("Enter an expense:")))

total = sum(expenses)

print("You spent $", total, sep='')

# Example store in variable 
total = 0 
expenses = []
num_expenses = int(input("Enter # of expenses:"))
for i in range(num_expenses ):
    expenses.append(float(input("Enter an expense:")))

total = sum(expenses)

print("You spent $", total, sep='')



